// <auto-generated />
using System;
using CareerProject.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CareerProject.Shared.Migrations
{
    [DbContext(typeof(CareerProjectDbContext))]
    [Migration("20260816162340_JobSkillRequiredLevelEnum")]
    partial class JobSkillRequiredLevelEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerProject.Shared.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PersonId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.PersonProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CvSummary")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonProfiles");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.PersonSkill", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PersonSkills");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a908eef-9fa3-4c1c-a091-0a351fd29f7f"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("f6e3e75e-f4c7-4445-a950-bdcd242a2766"),
                            Name = ".NET"
                        },
                        new
                        {
                            Id = new Guid("7151df15-375b-4fd8-bf53-ec4a99872f10"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("858b1dff-f15b-44fc-8335-849dd4c1e498"),
                            Name = "Spring Boot"
                        },
                        new
                        {
                            Id = new Guid("55f9afbb-f68b-4709-a189-8cffe25cec68"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("e8f70325-47ee-4e3b-8007-c25c7395daad"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("044ba8a0-51eb-41ed-a4a7-63d30b4835d3"),
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("faad0c20-7a75-4d57-8317-821b8d88cbb5"),
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("ee3eedd0-25c4-4633-9154-c8d34c9825ec"),
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("645360b7-3a40-4b6e-b2af-7c63ba8ab959"),
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("afff14fb-4893-49c0-9e13-c8b5a2fb97dc"),
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("2b87718d-b638-48d5-a8f5-0c2566974803"),
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("04bef3cb-a298-49b1-ae40-7921b7530b1b"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("7110b157-31c4-4683-9f44-909734f94196"),
                            Name = "Redis"
                        },
                        new
                        {
                            Id = new Guid("a205340a-6964-42e9-9322-7a52dd454811"),
                            Name = "RabbitMQ"
                        },
                        new
                        {
                            Id = new Guid("776a6a2c-c04b-4a1c-a294-439df0eadeed"),
                            Name = "Docker"
                        },
                        new
                        {
                            Id = new Guid("8a22c113-106f-42af-b5c4-7a23fe1ec239"),
                            Name = "Git"
                        },
                        new
                        {
                            Id = new Guid("af530ac8-9a3d-4628-ac00-f4262e35f226"),
                            Name = "REST API"
                        },
                        new
                        {
                            Id = new Guid("984edcb0-ef2a-4ede-9c31-e1d7008e8513"),
                            Name = "AWS"
                        });
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Application", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerProject.Shared.Entities.PersonProfile", "Person")
                        .WithMany("Applications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.ChatMessage", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.PersonProfile", "Person")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Company", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.User", "User")
                        .WithOne("Company")
                        .HasForeignKey("CareerProject.Shared.Entities.Company", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Job", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.JobSkill", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerProject.Shared.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.PersonProfile", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.User", "User")
                        .WithOne("PersonProfile")
                        .HasForeignKey("CareerProject.Shared.Entities.PersonProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.PersonSkill", b =>
                {
                    b.HasOne("CareerProject.Shared.Entities.PersonProfile", "Person")
                        .WithMany("PersonSkills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerProject.Shared.Entities.Skill", "Skill")
                        .WithMany("PersonSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Company", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.PersonProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ChatMessages");

                    b.Navigation("PersonSkills");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");

                    b.Navigation("PersonSkills");
                });

            modelBuilder.Entity("CareerProject.Shared.Entities.User", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("PersonProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
